### ISSUE TITLE
CC1101 firmware for mini-pro (8MHz!)

### ISSUE THREAD

**Issue by antst** [RFD-FHEM/RFFHEM#125] opened 2017-01-09 03:17 UTC
I tried to use included in dev33 firmware for CC1101, but it looks like it is compiled for Arduino Nano.
I use 3.3v mini pro (connected to ESP8266) which runs on 8MHz. 
I wanted to compile myself, but didn't find source of this firmware.

**Comment by antst** [comment] 2017-01-09 05:43
Found and recompiled myself. With the same result.
If CC1101 is present, it hangs after
Using sFIFO
Reading values fom eeprom
`CCInit
CCVersion=20
CCPartnum=0
Starting timerjob
receiver enabled
`

if I disconnect CC1101, it does not hang.

**Comment by antst** [comment] 2017-01-09 06:32
More to it.

It stucks in
`while (FiFo.count()>0 ) { //Puffer auslesen und an Dekoder uebergeben    
		aktVal=FiFo.dequeue();
	  state = musterDec.decode(&aktVal);     
		if (state) blinkLED=true; //LED blinken, wenn Meldung dekodiert
	}`

Fifo is filling faster than it can process.

**Comment by sidey79** [comment] 2017-01-09 08:41
Ist the cc1101 connected corrected. A Iteration of Kooperation should bei Taster than a normal Data Packet from the cc1101.

**Comment by antst** [comment] 2017-01-09 08:43
I compiled/flashed nanoCUL433 FW to this HW and it works perfectly, therefore I assume that there is no problem with HW.

**Comment by sidey79** [comment] 2017-01-09 16:42
Okay, the purpose of the ESP ist a WiFi or Serial bridge?

Normal loop time should bei lower than 90 uS, also on 8mhz versions.

Can you repeat the same result with another receicer connected or ist this a cc1101 specific problem?

**Comment by antst** [comment] 2017-01-10 11:24
ESP is a serial bridge over wifi.
But for simplicity I tried with wired connection, the same result.
I will try with Nano, just in case. I have 5 such modules, all of them with the same result on this setup with Pro Mini. And all of them works with nanoCUL firmware on Pro Mini.

Another question, how far SIGNALESP is from being working? Setup with arduino and ESP is a waste. ESP has way more capable controller than 328P, but used only as a bridge.

**Comment by sidey79** [comment] 2017-01-10 17:18
SignalEsp ist far from a reliable version.

1) The ESP resets very often and recovers without User interaction.
2) The WiFi processing adds lot of jitter in the Interrupt handling, because the interrupts are software interrupts.
May another approach is needed.

I'll try to build a pro mini with an cc1101 and reproduce this issue..

**Comment by sidey79** [comment] 2017-01-10 17:18
SignalEsp ist gar from a reliable version.

1) The ESP resets very often and Recovery without User interaction.
2) The WiFi processing prevents the Interrupt handling, because the Interrupts are software interrupts.

I'll try to build a pro mini with an cc1101 and reproduce this issue..

**Comment by sidey79** [comment] 2017-01-10 22:28
I've tested and reproduced the issue..
I think, the cc1101 is not set up with the correct registers and the interrupt is triggerd to often.

So the main loop can not handle incomming commands.

Workaround
disconnect pin2 
factory reset cc1101 with serial command e
reconnect pin2

**Comment by antst** [comment] 2017-01-11 11:17
Thanks! It worked!

Although now I have another problem, it doesn't look like it work smooth with my IT V3 remotes. Is there anything special about them? Do I better create devices by myself and not rely on autocreate?

**Comment by sidey79** [comment] 2017-01-11 17:07
Autocreate is a Fhem feature and implemented the IT Module.

As far i remember, two on commands are needed for proper autocreate withhin 30 seconds.

**Comment by Ralf9** [comment] 2017-01-11 18:56
there ist a problem with the autocreate with IT V3.
Here is a patch:
https://github.com/Ralf9/test/commit/cc4ae951995436baceb1202b5f49df1befc70504

**Comment by antst** [comment] 2017-01-27 14:55
BTW, about SignalESP.
There is RFM69GW project, which posts data received over RFM69 radio to MQTT. It works rather stable without hardware interrupts on ESP8266. Maybe you can borrow something.
https://bitbucket.org/xoseperez/rfm69gw

**Comment by sidey79** [comment] 2019-08-25 20:13
Here was no update for a while. I'll close this. Please repopen if needed.

**Closed by sidey79** 2019-08-25 20:13 UTC
