### ISSUE TITLE
00_SIGNALduino.pm MU: matching of start pattern: wrong? clarification/docs needed!!

### ISSUE THREAD

**Issue by andim2** [RFD-FHEM/RFFHEM#381] opened 2018-11-26 21:22 UTC
Hi,

this seems somewhat fishy to me, thus I'm asking about it.

Regarding branch dev-r33 FHEM/00_SIGNALduino.pm section (NOT doing code style since that thing seems PLAIN UNUSABLE to me):
                                Debug "startStr is: $startStr" if ($debug);
                                
                                if ($message_start = index($rawData, $startStr)) 
                                {
                                        $rawData = substr($rawData, $message_start);
                                        $startLogStr = "StartStr: $startStr first found at $message_start";
                                        Debug "rawData = $rawData" if ($debug);
                                        Debug "startStr $startStr found. Message starts at $message_start" if ($debug);
                                } else {
                                        Debug "startStr $startStr not found." if ($debug);
                                        next;
                                }

I'm truly wondering whether this $message_start conditional evaluation here is correct - I had a sample [unfortunately I cannot locate it any more] where startStr was to be found directly at string start, and where result of index() https://perldoc.perl.org/functions/index.html thus is 0, yet where
if ($message_start = index($rawData, $startStr))
then did NOT test against index() not-found (-1!!), thus directly-at-string-start was NOT accepted.
So:
- either index 0 truly is NOT acceptable for some reason - perhaps in order to prevent false-positive matches of initial strings improperly pulse-length-detected by the transceiver? (AND then this special/weird/non-obvious aspect OUGHT TO BE DOCUMENTED THERE [just like all non-obvious/peculiar/crucial handling in any code!])
  sample documentation text suggestion: "ignoring index 0 results since these might be unreliable (start-of-pulse-decoding transceiver data)"
- or index 0 IS acceptable --> BUG

Thanks!

**Comment by andim2** [comment] 2018-11-27 11:42
That's about what I had hoped for :)

If so, then
I'd suggest simply swapping the order of the two conditional bodies, since then
the conditional line would simply be changeable to directly match the other "eq -1" syntax of the conditional line above it.
I.e.
if ... -1) )
{
  Debug "startStr $startStr not found." if ($debug);
                                    next;
}
else
{
...
}

**Comment by sidey79** [comment] 2018-11-27 16:42
Ich hab mal schnell einen Test geschrieben, der diesen Bug auch findet :)

**Comment by Ralf9** [comment] 2018-11-27 17:03
@sidey79 da hast Du anscheinend in Deiner Version zu viel optimiert, bei meiner ursprünglicher Version hat es noch gepasst

**Comment by sidey79** [comment] 2018-11-28 20:56
@andim2 

Should be fixed in dev-r33 branch. Can you confirm?

**Comment by sidey79** [comment] 2018-12-03 20:53
@andim2 
Can you verify that the issue is fixed?

**Comment by andim2** [comment] 2018-12-04 17:04
My context info was pretty incomplete, sorry (thus I was not even sure any more which bell I had used to try this - ouch... ;).

However, with a clean
update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt
shutdown restart
(plus verbose 5, debug 1)
I am now getting (with HEIDEMANN HX) output such as:
$ tail -f log/fhem-2018-12.log|grep "first found at "
2018.12.04 17:37:18 5: sduino433: Starting demodulation (StartStr: 52 first found at 7 regex: (?:52)((?:34|12){12,}) Pos 7) length_min_max (12..12) length=12
2018.12.04 17:37:18 5: sduino433: Starting demodulation (StartStr: 51 first found at 26 regex: (?:51)((?:34|21){12,}) Pos 26) length_min_max (12..12) length=12
2018.12.04 17:37:18 5: sduino433: Starting demodulation (StartStr: 51 first found at 26 regex: (?:51)((?:34|21){12,}) Pos 26) length_min_max (12..12) length=12
2018.12.04 17:37:18 5: sduino433: Starting demodulation (StartStr: 61 first found at 26 regex: (?:61)((?:34|21){12,}) Pos 26) length_min_max (12..12) length=12
2018.12.04 17:37:19 5: sduino433: Starting demodulation (StartStr: 41 first found at 6 regex: (?:41)((?:23|01){12,}) Pos 6) length_min_max (12..12) length=12
2018.12.04 17:37:19 5: sduino433: Starting demodulation (StartStr: 51 first found at 26 regex: (?:51)((?:34|21){12,}) Pos 26) length_min_max (12..12) length=12
2018.12.04 17:37:19 5: sduino433: Starting demodulation (StartStr: 41 first found at 6 regex: (?:41)((?:23|01){12,}) Pos 6) length_min_max (12..12) length=12
2018.12.04 17:37:19 5: sduino433: Starting demodulation (StartStr: 61 first found at 26 regex: (?:61)((?:34|21){12,}) Pos 26) length_min_max (12..12) length=12
2018.12.04 17:37:19 5: sduino433: Starting demodulation (StartStr: 41 first found at 6 regex: (?:41)((?:23|01){12,}) Pos 6) length_min_max (12..12) length=12
2018.12.04 17:37:19 5: sduino433: Starting demodulation (StartStr: 41 first found at 14 regex: (?:41)((?:23|01){12,}) Pos 14) length_min_max (12..12) length=12

$ tail -f log/fhem-2018-12.log|grep "first found at 0"
2018.12.04 17:37:45 5: sduino433: Starting demodulation (StartStr: 01 first found at 0 regex: (?:01)((?:21|34){12,}) Pos 0) length_min_max (12..12) length=12
2018.12.04 17:37:55 5: sduino433: Starting demodulation (StartStr: 01 first found at 0 regex: (?:01)((?:34|21){12,}) Pos 0) length_min_max (12..12) length=12
2018.12.04 17:38:05 5: sduino433: Starting demodulation (StartStr: 01 first found at 0 regex: (?:01)((?:34|21){12,}) Pos 0) length_min_max (12..12) length=12

Taking a detailed look at decoding of one (17:38:05) of the above 0-based index() results:

2018.12.04 17:38:05 5: sduino433/RAW READ: /^BMU;P0=-4897;P1=324;P2=-637;P3=-310;P4=630;D=01213434212121342134342134012134342121213421343421340121343421212134213434213401213434212121342
134342134;CP=1;R=25;^C

2018.12.04 17:38:05 4: sduino433/msg READ: ^BMU;P0=-4897;P1=324;P2=-637;P3=-310;P4=630;D=012134342121213421343421340121343421212134213434213401213434212121342134342134012134342121213421
34342134;CP=1;R=25;^C
2018.12.04 17:38:05 1: DEBUG>sduino433: incoming message: (MU;P0=-4897;P1=324;P2=-637;P3=-310;P4=630;D=0121343421212134213434213401213434212121342134342134012134342121213421343421340121
3434212121342134342134;CP=1;R=25;)

2018.12.04 17:38:05 1: DEBUG>sduino433: extracted  pattern 0 -4897 

2018.12.04 17:38:05 1: DEBUG>sduino433: extracted  pattern 1 324 

2018.12.04 17:38:05 1: DEBUG>sduino433: extracted  pattern 2 -637 

2018.12.04 17:38:05 1: DEBUG>sduino433: extracted  pattern 3 -310 

2018.12.04 17:38:05 1: DEBUG>sduino433: extracted  pattern 4 630 

2018.12.04 17:38:05 1: DEBUG>sduino433: extracted  data 01213434212121342134342134012134342121213421343421340121343421212134213434213401213434212121342134342134

2018.12.04 17:38:05 1: DEBUG>sduino433: extracted  clockidx 1

2018.12.04 17:38:05 1: DEBUG>sduino433: extracted RSSI 25 

2018.12.04 17:38:05 1: DEBUG>sduino433: processing unsynced message

2018.12.04 17:38:05 1: DEBUG>Testing against Protocol id 8 -> TX3 Protocol
.
.
.
2018.12.04 17:38:05 1: DEBUG>Testing against Protocol id 79 -> m-e VTX-BELL
2018.12.04 17:38:05 1: DEBUG>Searching in patternList: $VAR1 = {
          '3' => '-0.9',
          '4' => '1.9',
          '2' => '-1.9',
          '0' => '-14.8',
          '1' => '1.0'
        };

2018.12.04 17:38:05 1: DEBUG>msgStartLst: $VAR1 = [
          -15,
          1
        ];

2018.12.04 17:38:05 1: DEBUG>tol: looking for (-15 +- 4.5)
2018.12.04 17:38:05 1: DEBUG>index => gap in tol (+- 4.5) of pulse (-15) : $VAR1 = {
          '0' => '0.199999999999999'
        };

2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 0
2018.12.04 17:38:05 1: DEBUG>tol: looking for (1 +- 1)
2018.12.04 17:38:05 1: DEBUG>index => gap in tol (+- 1) of pulse (1) : $VAR1 = {
          '1' => 0,
          '4' => '0.9'
        };

2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 1
2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 4
2018.12.04 17:38:05 1: DEBUG>looking for substr 01
2018.12.04 17:38:05 1: DEBUG>startStr is: 01
2018.12.04 17:38:05 1: DEBUG>rawData = 01213434212121342134342134012134342121213421343421340121343421212134213434213401213434212121342134342134
2018.12.04 17:38:05 1: DEBUG>startStr 01 found. Message starts at 0
2018.12.04 17:38:05 5: sduino433: substr: 01213434212121342134342134012134342121213421343421340121343421212134213434213401213434212121342134342134
2018.12.04 17:38:05 1: DEBUG>tol: looking for (-1 +- 1)
2018.12.04 17:38:05 1: DEBUG>index => gap in tol (+- 1) of pulse (-1) : $VAR1 = {
          '2' => '0.9',
          '3' => '0.1'
        };

2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 3
2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 2
2018.12.04 17:38:05 1: DEBUG>tol: looking for (2 +- 1)
2018.12.04 17:38:05 1: DEBUG>index => gap in tol (+- 1) of pulse (2) : $VAR1 = {
          '1' => 1,
          '4' => '0.1'
        };

2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 4
2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 1
2018.12.04 17:38:05 1: DEBUG>looking for substr 34
2018.12.04 17:38:05 1: DEBUG>Found matched one
2018.12.04 17:38:05 1: DEBUG>added 34 
2018.12.04 17:38:05 1: DEBUG>tol: looking for (-2 +- 1)
2018.12.04 17:38:05 1: DEBUG>index => gap in tol (+- 1) of pulse (-2) : $VAR1 = {
          '2' => '0.1'
        };

2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 2
2018.12.04 17:38:05 1: DEBUG>tol: looking for (1 +- 1)
2018.12.04 17:38:05 1: DEBUG>index => gap in tol (+- 1) of pulse (1) : $VAR1 = {
          '4' => '0.9',
          '1' => 0
        };

2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 1
2018.12.04 17:38:05 1: DEBUG>closest pattern has index: 4
2018.12.04 17:38:05 1: DEBUG>looking for substr 21
2018.12.04 17:38:05 1: DEBUG>Found matched zero
2018.12.04 17:38:05 1: DEBUG>added 21 
2018.12.04 17:38:05 4: sduino433: Fingerprint for MU Protocol id 79 -> m-e VTX-BELL matches, trying to demodulate
2018.12.04 17:38:05 1: DEBUG>signalRegex is (?:34|21){12,} 
2018.12.04 17:38:05 5: part is 213434212121342134342134 starts at position 0 and ends at 26
2018.12.04 17:38:05 5: sduino433: Starting demodulation (StartStr: 01 first found at 0 regex: (?:01)((?:34|21){12,}) Pos 0) length_min_max (12..12) length=12
2018.12.04 17:38:05 1: DEBUG>sduino433: demodulated message raw (0 1 1 0 0 0 1 0 1 1 0 1), 12 bits

2018.12.04 17:38:05 5: sduino433: dispatching hex: P79#62D



And the same thing with non-0 index (one can clearly see that the initial "23" --> -4890 / 333 combo starts at index 2 only):

2018.12.04 17:38:04 4: sduino433/msg READ: ^BMU;P0=-306;P1=643;P2=-4890;P3=333;P4=-639;D=012343010143434301430101430123430101434343014301014301234301014343430143010143012343010143434301
43010143012343010143434301430101430123430101434343014301014301234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143;CP=3;R=255;O;^C
2018.12.04 17:38:04 1: DEBUG>sduino433: incoming message: (MU;P0=-306;P1=643;P2=-4890;P3=333;P4=-639;D=0123430101434343014301014301234301014343430143010143012343010143434301430101430123
4301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143;CP=3;R=255;O
;)

2018.12.04 17:38:04 1: DEBUG>sduino433: extracted  pattern 0 -306 

2018.12.04 17:38:04 1: DEBUG>sduino433: extracted  pattern 1 643 

2018.12.04 17:38:04 1: DEBUG>sduino433: extracted  pattern 2 -4890 

2018.12.04 17:38:04 1: DEBUG>sduino433: extracted  pattern 3 333 

2018.12.04 17:38:04 1: DEBUG>sduino433: extracted  pattern 4 -639 

2018.12.04 17:38:04 1: DEBUG>sduino433: extracted  data 012343010143434301430101430123430101434343014301014301234301014343430143010143012343010143434301430101430123430101434343014301014
30123430101434343014301014301234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143

2018.12.04 17:38:04 1: DEBUG>sduino433: extracted  clockidx 3

2018.12.04 17:38:04 1: DEBUG>sduino433: extracted RSSI 255 

2018.12.04 17:38:04 1: DEBUG>sduino433: unknown Message part O
2018.12.04 17:38:04 1: DEBUG>sduino433: processing unsynced message

2018.12.04 17:38:04 1: DEBUG>Testing against Protocol id 8 -> TX3 Protocol
.
.
.
2018.12.04 17:38:04 1: DEBUG>Testing against Protocol id 79 -> m-e VTX-BELL
2018.12.04 17:38:04 1: DEBUG>Searching in patternList: $VAR1 = {
          '2' => '-14.8',
          '4' => '-1.9',
          '1' => '1.9',
          '0' => '-0.9',
          '3' => '1.0'
        };

2018.12.04 17:38:04 1: DEBUG>msgStartLst: $VAR1 = [
          -15,
          1
        ];

2018.12.04 17:38:04 1: DEBUG>tol: looking for (-15 +- 4.5)
2018.12.04 17:38:04 1: DEBUG>index => gap in tol (+- 4.5) of pulse (-15) : $VAR1 = {
          '2' => '0.199999999999999'
        };

2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 2
2018.12.04 17:38:04 1: DEBUG>tol: looking for (1 +- 1)
2018.12.04 17:38:04 1: DEBUG>index => gap in tol (+- 1) of pulse (1) : $VAR1 = {
          '3' => 0,
          '1' => '0.9'
        };

2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 3
2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 1
2018.12.04 17:38:04 1: DEBUG>looking for substr 23
2018.12.04 17:38:04 1: DEBUG>startStr is: 23
2018.12.04 17:38:04 1: DEBUG>rawData = 234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143
2018.12.04 17:38:04 1: DEBUG>startStr 23 found. Message starts at 2
2018.12.04 17:38:04 5: sduino433: substr: 234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143010143012343010143434301430101430123430101434343014301014301234301014343430143
2018.12.04 17:38:04 1: DEBUG>tol: looking for (-1 +- 1)
2018.12.04 17:38:04 1: DEBUG>index => gap in tol (+- 1) of pulse (-1) : $VAR1 = {
          '0' => '0.1',
          '4' => '0.9'
        };

2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 0
2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 4
2018.12.04 17:38:04 1: DEBUG>tol: looking for (2 +- 1)
2018.12.04 17:38:04 1: DEBUG>index => gap in tol (+- 1) of pulse (2) : $VAR1 = {
          '3' => 1,
          '1' => '0.1'
        };

2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 1
2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 3
2018.12.04 17:38:04 1: DEBUG>looking for substr 01
2018.12.04 17:38:04 1: DEBUG>Found matched one
2018.12.04 17:38:04 1: DEBUG>added 01 
2018.12.04 17:38:04 1: DEBUG>tol: looking for (-2 +- 1)
2018.12.04 17:38:04 1: DEBUG>index => gap in tol (+- 1) of pulse (-2) : $VAR1 = {
          '4' => '0.1'
        };

2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 4
2018.12.04 17:38:04 1: DEBUG>tol: looking for (1 +- 1)
2018.12.04 17:38:04 1: DEBUG>index => gap in tol (+- 1) of pulse (1) : $VAR1 = {
          '1' => '0.9',
          '3' => 0
        };

2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 3
2018.12.04 17:38:04 1: DEBUG>closest pattern has index: 1
2018.12.04 17:38:04 1: DEBUG>looking for substr 43
2018.12.04 17:38:04 1: DEBUG>Found matched zero
2018.12.04 17:38:04 1: DEBUG>added 43 
2018.12.04 17:38:04 4: sduino433: Fingerprint for MU Protocol id 79 -> m-e VTX-BELL matches, trying to demodulate
2018.12.04 17:38:04 1: DEBUG>signalRegex is (?:01|43){12,} 
2018.12.04 17:38:04 5: part is 430101434343014301014301 starts at position 0 and ends at 26
2018.12.04 17:38:04 5: sduino433: Starting demodulation (StartStr: 23 first found at 2 regex: (?:23)((?:01|43){12,}) Pos 2) length_min_max (12..12) length=12
2018.12.04 17:38:04 1: DEBUG>sduino433: demodulated message raw (0 1 1 0 0 0 1 0 1 1 0 1), 12 bits

2018.12.04 17:38:04 5: sduino433: dispatching hex: P79#62D


Thus, from a semi-cursory look, it seems fixed and working :)

Thank you very much!
(of course I wouldn't have had a nice opportunity to thank you plenty for this very nice project work if it had been working in the first place :)))
((that's the administrator's curse - as long as systems are working, due to an admin genius, users are bored to death and swearing, yet once things happen to fall apart, due to an imperfect admin, they'll be eternally grateful for having it fixed again :)))

**Comment by sidey79** [comment] 2018-12-04 19:51
I've closed this, because we think the isse is fixed. Thank you for reporting.
Feel free to reopen this one or a new one if there is again such a problem.

**Closed** 2018-12-04 19:51 UTC
Labels: bug, probably ready
